[LootGlow]
; Containers glow when they contain this much gold or more.
GoldCountThreshold=10

; Set to 0 to disable glow for valuable non-gold loot.
HighValueMode=1

; Containers glow when they contain loot worth this much or more.
HighValueThreshold=50

; Set to 1 to enable glow for containers with lockpicks.
LockpickMode=0

; Set to 1 to enable glow for containers whose contents equal the threshold in total, but individually do not meet the threshold
HighValueAggregateMode=0
